[project]
name = "reflective-learning"
version = "0.1.0"
description = "Reflective Learning"
license = "Apache-2.0"
dependencies = [
    "torch"
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = ["pytest"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
